### ISSUE TITLE
[Register] Change alert with an UI error component

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#30]
Find in the code the following comment:
`// TODO: Change alert with an UI error component`
And make an UI error component that shows the error to the user (probably only needed at step 3)
An example:

![Image](https://github.com/tineret-spearanta-oradea/hopecamp-website/assets/92709351/2d756a23-3455-49ec-bc9e-dcf28c0c97db)

**Comment by ghefraim** [comment]
Hey @MaxiFrancis , are you still working on this issue?
This ticket is high-priority at this time, so I'd rather take it, and give you another one

**Comment by MaxiFrancis** [comment]
Well, I was working. I do not know exactly how to correctly trigger the errors. You can take the ticket.
I deleted the alerts and created a logic, to pass the error message as prop. Since it is called in Index I passed it to MultiSteepForm, and form the re to Step, and than I used the ErrorAlert component to show the message in the top of the form.

**Comment by ghefraim** [comment]
Okay, thanks

**Comment by ghefraim** [comment]
Coding done. Can be tested.

1. Go to register form
2. Enter an email that was used before
3. on the last step, you can see an error

There are multiple causes that can create an error. but this is one of them.

You can also see an error at login, when you try to login with invalid email

Also, please check that if there are no errors, the flow works correctly (register and login)

**Comment by ddardistrugatoru** [comment]
The alerts are working.
