### ISSUE TITLE
Changes after feedbacks

### ISSUE THREAD

**Issue by ghefraim** [tineret-spearanta-oradea/hopecamp-website#91]
- [x] start date and end date can be manually inputed with text. change that!
- [x] home button near logout button would be helpful
- [x] safari admins - invalid date error on update user
- [x] admins mobile open without sidebar
- [x] one COLUMN on FAQ desktop
- [x] add "Cont" button in homepage navbar
- [x] add some animations (homepage)

**Comment by ddardistrugatoru** [comment]
1 -> works
2 -> works
3 -> i ll come up later with the feedback, i can t acces it on safari right now
4 -> i ll come up later with the feedback, i can t acces it on safari right now
5 -> works
6 -> works
7 -> the animations are lookin' smooth but there is one thing that i don t like, when you re goin on homepage the buttons should be hided until the animation is clear or setparentin on the  background because the animation it s goin up and down and you can see them before the animation is done
https://github.com/tineret-spearanta-oradea/hopecamp-website/assets/63541756/0819e2c8-f5a2-4aac-80aa-909ebfd5d949

**Comment by ghefraim** [comment]
Fixed.
